// Implemented for spec: agent/specs/meal-appointment-participation-frontend-implementation-spec.md

export const participationStrings = {
  pageTitle: '가용 시간 제출',
  helpTitle: '참여 안내',
  helpDescription: '닉네임은 1~30자, PIN은 선택 입력(4~12자)입니다. 제출 후에도 언제든지 수정할 수 있어요.',
  startParticipation: '참여 시작',
  submitAvailability: '가용 시간 제출',
  resetSelection: '초기화',
  loading: '약속 정보를 불러오는 중입니다',
  notFound: '약속을 찾을 수 없습니다',
  retry: '재시도',
  nicknameLabel: '닉네임',
  pinLabel: 'PIN(선택)',
  saveToDevice: '현재 기기 저장',
  saveWarning: '암호화 없이 닉네임과 PIN을 저장합니다.',
  existingResponse: '이전에 제출한 응답을 불러왔어요',
  invalidPin: 'PIN이 일치하지 않습니다',
  nicknameTaken: '이미 사용 중인 닉네임입니다',
  invalidSlot: '선택한 슬롯이 템플릿에 없어요',
  temporaryFailure: '일시적인 오류가 발생했습니다. 다시 시도해 주세요.',
  networkError: '네트워크에 연결할 수 없습니다',
  submitSuccess: '가용 시간을 제출했어요',
  toggleInstruction: '요일별로 가능한 식사 시간을 선택하세요.',
  summaryTitle: '요약',
  selectedCount: (count: number) => `선택됨 ${count}개`,
  unselectedCount: (count: number) => `미선택 ${count}개`,
  overwriteWarning: '이전에 제출한 응답이 새로 저장됩니다.',
  lastSubmittedAt: (timestamp: string) => `마지막 제출: ${timestamp}`,
  helpCta: '도움말',
  refresh: '새로고침',
  slotAvailableCount: (available: number, total: number) => `${available}/${total}`,
  emptySlots: '선택할 수 있는 슬롯이 없습니다',
  mobileOverflowLabel: '메뉴'
};
